general.import = [ "/usr/lib/node_modules/alacritty-themes/themes/XTerm.toml" ]


[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
opacity = 0.9
blur = false
option_as_alt = "Both"

  [window.padding]
  x = 10
  y = 10

[font]
size = 15

  [font.normal]
  family = "MesloLGS Nerd Font Mono"
