general.import = [ "~/.config/alacritty/themes/themes/coolnight.toml" ]


#general.import = [ "/usr/lib/node_modules/alacritty-themes/themes/XTerm.toml" ]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
opacity = 0.8
blur = true
option_as_alt = "Both"

[window.padding]
x = 10
y = 10

[font]
size = 12
normal = { family = "MesloLGS Nerd Font Mono", style = "Regular" }
bold = { family = "MesloLGS Nerd Font Mono", style = "Bold" }
italic = { family = "MesloLGS Nerd Font Mono", style = "Italic" }
bold_italic = { family = "MesloLGS Nerd Font Mono", style = "Bold Italic" }





[keyboard]
bindings = [
  { key = "CapsLock", mods = "Control", action = "None" }
]

