# --- [ 1. General Config ] ---
"$schema" = 'https://starship.rs/config-schema.json'

# This adds a blank line ABOVE the prompt (gap between commands)
add_newline = true

# 2-line format: Metadata on line 1, Input on line 2.
format = """
╭[](#6689bd)\
$os\
$username\
[](bg:#878fb3 fg:#6689bd)\
$directory\
[](fg:#878fb3 bg:#7ca879)\
$git_branch\
$git_status\
[](fg:#7ca879 bg:#66a5b0)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$python\
[](fg:#66a5b0 bg:#45475a)\
$docker_context\
[](fg:#45475a bg:#313244)\
$time\
[ ](fg:#313244)
╰─$character """

palette = 'catppuccin_mocha_dimmed'

[palettes.catppuccin_mocha_dimmed]
blue = "#6689bd"
lavender = "#878fb3"
green = "#7ca879"
sky = "#66a5b0"
base = "#1e1e2e"
text = "#cdd6f4"
surface1 = "#45475a"
surface0 = "#313244"

# --- [ 2. Modules ] ---

[os]
disabled = false
style = "bg:#6689bd fg:#1e1e2e"

[os.symbols]
Arch = "󰣇 "
Linux = "󰌽 "

[username]
show_always = true
style_user = "bg:#6689bd fg:#1e1e2e"
style_root = "bg:#6689bd fg:#1e1e2e"
format = '[$user]($style)'

[directory]
style = "fg:#1e1e2e bg:#878fb3"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#7ca879"
format = '[[ $symbol $branch ](fg:#1e1e2e bg:#7ca879)]($style)'

[git_status]
style = "bg:#7ca879"
format = '[[($all_status$ahead_behind )](fg:#1e1e2e bg:#7ca879)]($style)'

[nodejs]
symbol = ""
style = "bg:#66a5b0"
format = '[[ $symbol( $version) ](fg:#1e1e2e bg:#66a5b0)]($style)'

[rust]
symbol = ""
style = "bg:#66a5b0"
format = '[[ $symbol( $version) ](fg:#1e1e2e bg:#66a5b0)]($style)'

[python]
symbol = ""
style = "bg:#66a5b0"
format = '[[ $symbol( $version) ](fg:#1e1e2e bg:#66a5b0)]($style)'

[docker_context]
symbol = " "
style = "bg:#45475a"
format = '[[ $symbol( $context) ](fg:#66a5b0 bg:#45475a)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#313244"
format = '[[  $time ](fg:#cdd6f4 bg:#313244)]($style)'

[character]
disabled = false
success_symbol = '[](bold green)'
error_symbol = '[](bold red)'
