# Pomodoro Configuration
TEST_MODE="OFF"
BREAK_LOCK_DELAY_SEC_DEFAULT=30
BREAK_LOCK_DELAY_SEC_TEST=3
WORK_DURATION_DEFAULT="25m"
SHORT_BREAK_DURATION_DEFAULT="5m"
LONG_BREAK_DURATION_DEFAULT="15m"
WORK_DURATION_TEST="15s"
SHORT_BREAK_DURATION_TEST="15s"
LONG_BREAK_DURATION_TEST="15s"
EVENING_LOCK_ENABLED="OFF"
LOCK_START_TIME_CONFIG="1930"
LOCK_FREQUENCY_CONFIG="10"
