general.import = [ "/usr/lib/node_modules/alacritty-themes/themes/XTerm.toml" ]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
opacity = 0.8
blur = true
option_as_alt = "Both"

  [window.padding]
  x = 10
  y = 10

[font]
size = 12

  [font.normal]
  family = "MesloLGS Nerd Font Mono"


