# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = sleep 10 && uwsm-app -- hyprsunset --temperature 4000
exec-once = brave http://localhost:8384
exec-once = sticky

# Command Center Startup
exec-once = ghostty --font-size=14
exec-once = brave
exec-once = obsidian

#exec-once = xdg-open 'obsidian://open?file=000_SCRATCHPAD_Brain_Dump'
