# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

# Vertical monitor to the left
monitor = HDMI-A-1,1920x1080@60,0x0,1,transform,1

# Main horizontal monitor to the right (adjusted for 1-inch elevation)
monitor = DP-1,1920x1080@60,1080x740,1
# Future use: Uncomment the line below for Ultrawide in Triple Setup (Requires shifting DP-2 position)
# monitor = DP-1,3440x1440@60,1080x0,1

# Reserved monitor (Centered vertically relative to the main monitor)
monitor = DP-2,1920x1080@60,3000x320,1,transform,3

### Ultrawide Mode Setup
# To enable side monitors, uncomment these lines and comment out the 'disable' lines below:
# monitor = HDMI-A-1,1920x1080@60,0x0,1,transform,1
# monitor = HDMI-A-1,disable

# monitor = DP-1,3440x1440@60,0x0,1

# monitor = DP-2,1920x1080@60,4520x0,1,transform,3
# monitor = DP-2,disable

# Persistence Rules
workspace = 1, monitor:HDMI-A-1, default:true
workspace = 2, monitor:DP-1, default:true
workspace = 3, monitor:DP-2, default:true

